[SDK-4952]Updated Readme
jwplayer/jwplayer-android-best-practice-apps pull request #29
Opened 2019-12-20 00:36 UTC by GMSyrimis

### What does this Pull Request do?
Updates the readme to include all projects (RecyclerView has a PR ready)

### Why is this Pull Request needed?
The old instructions are outdated

### Are there any points in the code the reviewer needs to double check?
No

### Are there any Pull Requests open in other repos which need to be merged with this?
Approving this would be helpful:
https://github.com/jwplayer/jwplayer-android-best-practice-apps/pull/28

#### Addresses Issue(s):

SDK-4952

2019-12-23 19:30 UTC, henryhlee approved these changes

2019-12-24 15:51 UTC, paulmandal commented on README.md
> +- **FullBackgroundAudio**	- A demo of how you can setup the player to allow for background audio playback
Some of these have a space after the demo name and others have a tab

2019-12-24 15:51 UTC, paulmandal requested changes
Left one comment re: spaces vs tabs, otherwise it looks good.

2019-12-24 15:52 UTC, paulmandal commented on README.md
> +- Lastly, open the **AndroidManifest.xml** file and replace `{YOUR_LICENSE_KEY` with your **Android SDK 3** license key. You can find the license key in your dashboard under **Players > Downloads & K
Missing the closing brace on `YOUR_LICENSE_KEY`

2020-01-07 02:33 UTC, paulmandal approved these changes
LGTM!

2020-01-15 17:06 UTC, merged