JWSDK (v3 only) VUDRM Widevine online integration no sdk
jwplayer/jwplayer-android-best-practice-apps pull request #526
Opened 2021-11-23 16:58 UTC by macmagician

JWSDK v3 (only) VUDRM Widevine online integration rebase
Created separate module to preserve original source
Amended required configs to throw syntax error and marked as TODO

2021-11-23 17:07 UTC, paulmandal approved these changes
Looks good to me!

2021-11-23 17:08 UTC, GMSyrimis requested changes

2021-11-23 17:08 UTC, GMSyrimis commented on VUDRMWidevineDemo/app/src/main/AndroidManifest.xml
> +        <meta-data
License keys are now set programmatically.

2021-11-23 17:08 UTC, GMSyrimis commented on VUDRMWidevineDemo/app/build.gradle
> +        applicationId "com.jwplayer.demo.recyclerview"
May want to change this to match your demo

2021-11-23 17:08 UTC, GMSyrimis commented on VUDRMWidevineDemo/app/src/main/AndroidManifest.xml
> +    package="com.jwplayer.demo.recyclerview">
May want to change this to match your demo

2021-11-23 17:08 UTC, GMSyrimis commented on VUDRMWidevineDemo/app/src/main/java/com/jwplayer/demo/recyclerview/MainActivity.java
> +	public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
Any particular reason you chose to include the RecyclerView in your demo? It adds complexity to the demo distracting the developer from required code and optional code.

2021-11-24 17:58 UTC, GMSyrimis approved these changes

2022-01-26 16:14 UTC, merged