[SERV-12208] Update DRM demo
jwplayer/jwplayer-android-best-practice-apps pull request #691
Opened 2022-09-30 18:22 UTC by Jmilham21

### What does this Pull Request do?
Simplifies and documents the DRM demo best practice app

### Why is this Pull Request needed?
There has been confusion for customers on how this app works and it didn't match our documentation

### Are there any points in the code the reviewer needs to double check?
The Gradle version bump

### Are there any Pull Requests open in other repos which need to be merged with this?
No

#### Addresses Issue(s):

SERV-12208

2022-10-18 08:21 UTC, bengo1990 approved these changes
Looks good! I think the changes will make this a lot more easier for customers to use.

2022-10-18 09:15 UTC, macmagician approved these changes
All good, should now be much easier for devs at every level to get DRM up and running.

2022-12-07 17:52 UTC, GMSyrimis requested changes, later dismissed

2022-12-07 17:52 UTC, GMSyrimis commented on DrmDemo/app/build.gradle
> +	def exoplayerVersion = '2.16.1'
We don't need the `exoplayerVersion` when setting up with maven

2022-12-07 19:00 UTC, gilinho9002 approved these changes

2022-12-08 17:23 UTC, merged